puts "marina".object_id
puts "marina".object_id
puts "marina".object_id
puts "marina".object_id
puts '-----------------'
puts :marina.object_id
puts :marina.object_id
puts :marina.object_id
puts :marina.object_id